<script lang="ts">
  import logo from './assets/images/svelte.png'
  import Counter from './lib/Counter.svelte'
  import { Greet } from '../wailsjs/go/main/App';

  let name = "";
  let greeting = "";

  function greet() {
    Greet(name).then((result) => {
      greeting = result;
    });
  }
</script>



<main class="text-center h-screen bg-gray-900 text-white">
  <img src={logo} alt="Svelte Logo" class="h-64 w-64 mx-auto mt-8" />
  <h1 class="text-3xl font-bold underline text-emerald-700 mt-8">
    Hello world!
  </h1>

  <Counter />

  <p class="max-w-sm mx-auto my-4">
    Visit <a href="https://svelte.dev" class="text-blue-400">svelte.dev</a> to learn how to build Svelte
    apps.
  </p>

  <p class="max-w-sm mx-auto my-4">
    Check out <a href="https://github.com/sveltejs/kit#readme" class="text-blue-400">SvelteKit</a> for
    the officially supported framework, also powered by Vite!
  </p>

  <hr class="my-8 border-gray-700">

  <p class="my-4">This tests that the Go functionality is working too. The greeting is generated by Go.</p>
  <div id="input" class="mb-4 data-wails-no-drag">
    <label class="block text-sm font-bold mb-2" for="name">
      Name
    </label>
    <input id="name" type="text" bind:value={name} class="shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2" on:click={greet}>Greetings</button>
  </div>
  {#if greeting}
    <div id="result" class="mt-4 text-lg">{greeting}</div>
  {/if}
</main>

<style>
  @font-face {
    font-family: "Nunito";
    font-style: normal;
    font-weight: 400;
    src: local(""),
    url("assets/fonts/nunito-v16-latin-regular.woff2") format("woff2");
}
</style>
